Add Hall Office Members
abdatta/hall3-home pull request #50
Opened 2024-03-15 22:12 UTC by mk0380

2024-03-16 21:38 UTC, abdatta commented on ngx-cropper/ngx-cropper.component.css
Why did we move `ngx-cropper` outside of src/app?

2024-03-17 02:32 UTC, mk0380 commented on ngx-cropper/ngx-cropper.component.css
There is another ngx-cropper in src/app/modules; deleting the one that you are mentioning is failing the npm start command. So I don't think that's going to cause any issues.

2024-03-17 09:05 UTC, abdatta commented on ngx-cropper/ngx-cropper.component.css
It shouldn't be placed on root level. Ecery component should be inside a module. 
Also can you add some descriptions for each of your change. There are way too many changes to review.

2024-03-17 11:45 UTC, abdatta requested changes
I've pushed some of the changes in branch `pr/50`. You can take a pull from there.

2024-03-17 11:45 UTC, abdatta commented on src/app/modules/administration/hall_office/hall_office.component.html
Keep the style of email/phno/etc. consistent with other tiles used in HECs

2024-03-17 11:45 UTC, abdatta commented on src/app/modules/home/gallery/gallery.component.ts
Let's remove gallery components from this PR

2024-03-17 11:45 UTC, abdatta commented on src/app/modules/administration/hall_office/hall_office.component.ts
naming convention: use dashes `-` instead of underscores `_`. So `hall-office` instead of `hall_office`

2024-03-17 11:45 UTC, abdatta commented on src/app/modules/administration/ex_hec/ex_hec.component.ts
let's remove ex_hec components from this PR

2024-03-18 04:22 UTC, abdatta requested changes
Minor nit comments. Otherwise looks good to me.
Note: I think you skipped the spec test file in the hall_office component, which is fine since we do not run tests for this repo, but for consistency you can add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/home/home.router.ts
> +export class HomeRouterModule {}
This file shouldn't be modified. You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/people/people.module.ts
> +export class PeopleModule {}
This file shouldn't be modified. You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/tiles/tiles.module.ts
> +export class TilesModule {}
This file shouldn't be modified. You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/home/home.module.ts
> +export class HomeModule {}
This file shouldn't be modified. You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/services/main/main.service.ts
> +}
You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/administration/administration.router.ts
> +export class AdministrationRouterModule {}
You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on src/app/modules/administration/administration.module.ts
> +export class AdministrationModule {}
You've removed a newline at the end. Please add it back.

2024-03-18 04:22 UTC, abdatta commented on package.json
> +}
You've removed a newline at the end. Please add it back.

2024-03-18 13:22 UTC, abdatta approved these changes

2024-03-19 14:46 UTC, merged